export const GET_DOGS = 'GET_DOGS';
export const GET_ID = "GET_ID";
export const GET_RAZAS = "GET_RAZAS";
export const GET_TEMP = "GET_TEMP";
export const POST_DOGS = "POST_DOGS";
export const SET_SELECTED_TEMPERAMENT = "SET_SELECTED_TEMPERAMENT";
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_SHOW_API_DOGS = 'SET_SHOW_API_DOGS';
export const SET_SHOW_BDD_DOGS ='SET_SHOW_BDD_DOGS'
export const SET_SHOW_BOTH_DOGS ='SET_SHOW_BOTH_DOGS';